import { PUBLIC_APP_ENDPOINT } from '$env/static/public';

export {
  PUBLIC_APP_ENDPOINT as APP_ENDPOINT,
  PUBLIC_CHROME_EXTENSION_URL as CHROME_EXTENSION_URL,
  PUBLIC_DOMAIN as DOMAIN,
  PUBLIC_DOMAIN_ALIAS as DOMAIN_ALIAS,
  PUBLIC_FIREFOX_EXTENSION_URL as FIREFOX_EXTENSION_URL
} from '$env/static/public';

export const SIGNUP_URL = PUBLIC_APP_ENDPOINT + '/signup';
